### ISSUE TITLE
Bộ lọc và tìm kiếm ở ContestStanding 

### ISSUE THREAD

**Issue by nvatuan** [BKDN-University/bkdnOJ-v2#29]
Lọc thí sinh theo tổ chức, hay chỉ theo dõi một số thí sinh nhất định. Bộ lọc này chắc sẽ chỉ ở Front-end vì phía Back-end mình đã return tất cả những đối tượng liên quan rồi. Có thể tham khảo domJudge như sau:
![image](https://user-images.githubusercontent.com/24392632/183612118-581606c4-96e3-4fdf-be4a-0000c666b212.png)

**Comment by nvatuan** [comment]
Khách hàng dí:
> Bảng scoreboard cần hiển thị tên University, lọc được các đội/các University muốn xem. (lọc trên front-end)

**Comment by nvatuan** [comment]
Related pull: https://github.com/BKDN-University/bkdnOJ-reborn-frontend/pull/13

**Comment by trinhdvt** [comment]
đỉnh rứa bro

**Comment by nvatuan** [comment]
Có một vấn đề nhỏ, người đang ở standing nếu chuyển tab sang Problem, Submission rồi chuyển về sẽ bị mất bộ lọc. Điều này là do Standing bị unmount làm mất state. Có thể sử dụng Redux giữ trạng thái bộ lọc trong khi app còn mở.

**Comment by nvatuan** [comment]
OK Merged
