### ISSUE TITLE
[ENHANCE] Hiển thị vị trí của người tham gia hiện tại trên Standing

### ISSUE THREAD

**Issue by trinhdvt** [BKDN-University/bkdnOJ-v2#39]
Ở trang Standing, cần thêm một button để xác định vị trí của người tham gia hiện tại trên bxh.

**Comment by trinhdvt** [comment]
Link PR: https://github.com/BKDN-University/bkdnOJ-reborn-frontend/pull/16

**Comment by nvatuan** [comment]
OK merged
