### ISSUE TITLE
[FEATURE] Contest Homepage để hiển thị thông tin về cuộc thi trước khi nó bắt đầu

### ISSUE THREAD

**Issue by nvatuan** [BKDN-University/bkdnOJ-v2#41]

**Comment by trinhdvt** [comment]
PR: https://github.com/BKDN-University/bkdnOJ-reborn-frontend/pull/18

**Comment by nvatuan** [comment]
Gửi @trinhdvt tạm cái mock screen (mspaint thập niên 90), xài tạm đi để hồi học figma.
![image](https://user-images.githubusercontent.com/24392632/185868287-cfbd9e59-ec8c-414d-a2a2-78c0f4c909ae.png)

Nhờ bro cải tiến thêm xíu nữa chớ trông hơi buồn

**Comment by trinhdvt** [comment]
đỉnh rứa bro, ok bro 🍶 🥇

**Comment by nvatuan** [comment]
Quên mất, `authors` có thể rỗng vì không muốn lộ danh tính (lộ danh tính = lộ pattern ra đề), nhờ Trình handle chỗ đó luôn, có thể hiển thị `Contest Authors hidden.` màu xám, in nghiên.

**Comment by trinhdvt** [comment]
Có một lỗi khá là kì cục, cùng 1 API nhưng kết quả ở chrome dev tool lại khác khi mở trực tiếp, cụ thể là ở trường `register_allow`
- Kết quả ở dev tool
![Ảnh chụp Màn hình 2022-08-27 lúc 23 04 28](https://user-images.githubusercontent.com/45824015/187038375-6e2b499a-abc6-4f81-8b51-a66ae49a263d.png)

- Kết quả khi mở trực tiếp
![Ảnh chụp Màn hình 2022-08-27 lúc 23 05 03](https://user-images.githubusercontent.com/45824015/187038376-7830135a-359f-4df9-a76d-12ed5faeb57c.png)

**Comment by nvatuan** [comment]
Mở trực tiếp nó gửi lại request mà không có header Authorization thì phải, Trình login cái API thử chưa

**Comment by trinhdvt** [comment]
à, ok bro, login vào thì nó hiện lại đúng. Mà nếu như vậy thì hiện tại vẫn đăng ký vào Contest này được trong nó quá `end_time` rồi.

**Comment by trinhdvt** [comment]
Rứa thì có cần check theo `end_time` hay `fronzen_time` hay điều kiện khác để block đăng ký nữa k bro

**Comment by nvatuan** [comment]
Chắc chỉ cần `register_allow` thôi á

**Comment by trinhdvt** [comment]
> Chắc chỉ cần `register_allow` thôi á

ok bro. Đi ngủ mai xem OG bro kkk

**Comment by nvatuan** [comment]
Bet xí chứ hết tiền rồi

**Comment by trinhdvt** [comment]
- Cái vụ mà hiển thị màu của author thì tui k thấy màu trong API nhỉ ?
- Giao diện tạm thời trông như này:
![image](https://user-images.githubusercontent.com/45824015/187041305-d37e4dbe-e281-4c60-a834-522d9fc50791.png)

**Comment by nvatuan** [comment]
Ok bro chắc tôi thiếu gì rồi

**Comment by nvatuan** [comment]
Cái duration thêm text Length hay Duration cho rõ đi a Trình

**Comment by trinhdvt** [comment]
> Cái duration thêm text Length hay Duration cho rõ đi a Trình

Là hiện dạng như kiểu `Duration: 48h` à hay sao bro nhỉ

**Comment by nvatuan** [comment]
Uk như thế đi, a Trình thấy sao

**Comment by trinhdvt** [comment]
> Uk như thế đi, a Trình thấy sao

Cũng được, để tui sửa lại
