### ISSUE TITLE
da nang codeleague

### ISSUE THREAD

**Issue by hieuhoicoi** [BKDN-University/bkdnOJ-v2#59]
### Reporter: 
- In-charge: @author1
- Supporter: @author2

# BUSINESS
## Actors
- *Relatable actor 1*
- *Relatable actor 2*

## Problems
- *Which actor suffers which problem? What new features or new changes do they need implemented?*

## Background
- *What we already have? What other team have for us? Which running EPIC is blocking or duplicates some requirements? What in the world is affecting us?*

## Goals
- *What are we trying to achieve?*

## Value
- *If DONE, who will benefits from it? In aspect of Data, new users, influence,..?*

# USER EXPERIENCE
*Below lists User Stories, User Journeys. From which screen, with which action, users get taken to where and what will be achieved?*
## User Story 1
- Starts at Screen A
- User click B
...

# ARCHITECTURE DESIGN
*This step analyzes above features, and devise a plan for all related components of project (Backend, Frontend, Mobile,...). The required output for this step is a Technical Design Document.*
- TDD: Link Here

**Comment by nvatuan** [comment]
Chào bạn, 
Mình rất tiếc vì trải nghiệm không tốt của bạn tại Đà Nẵng Code League.
Nhưng team thực hiện project này và đội ngũ DN Code League là hai tổ chức khác nhau, chúng tôi không thể giúp cho bạn được.
Chúng tôi sẽ gửi lời đến với ban tổ chức để lần sau có thể làm tốt hơn.
Xin cảm ơn bạn.
